languageName: English
params:
  description: Why OpenMS? Mass Spectrometry. Visualizations. Open source.
  navbarlogo:
    image: openms-logo.png
    link: /
  hero:
    # Main hero title
    # title: OpenMS
    # Hero subtitle (optional)
    subtitle: The open-source framework for Mass Spectrometry
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "/install"
    # Hero image (from static/images/___)
    image: openms-logo.png

  heroGroup:
  - title: "OpenMS allows users to:"
    bgColor: ECF2F9
    heroItems:
    - title: Run existing workflows
      subtitle: Run existing workflows for proteomics and metabolomics with OpenMS in KNIME.
      leftAlign: true
      image: knime-analytics.png
      buttonText: Get Started
      buttonLink: "https://openms.readthedocs.io/en/latest/run-workflows-with-openms-tools/openms-in-knime.html"
    - title: Create your own workflows
      subtitle: Modify and create your own OpenMS workflows in Galaxy, KNIME and Nextflow.
      image: knime-edit.png
      buttonText: Get Started
      buttonLink: "https://openms.readthedocs.io/en/latest/run-workflows-with-openms-tools/overview.html"
    - title: Use OpenMS in Python
      subtitle: Enhance workflows with pyOpenMS scripts or develop novel methods using pyOpenMS
      leftAlign: true
      image: pyopenms4.png
      imgClass: pyopenms-img
      bottomBorderRadius: true
      buttonText: Get Started
      buttonLink: "https://pyopenms.readthedocs.io/en/latest/"
  - title: "Advanced users / developers can use OpenMS to:"
    bgColor: FFF1E0
    heroItems:
    - title: Analyze large datasets
      subtitle: Run workflows on very large datasets on powerful compute infrastructure
      leftAlign: true
      imgClass: nfcore-img
      image: nf-core-logo.png
      buttonText: Get Started
      buttonLink: "https://openms.readthedocs.io/en/latest/run-workflows-with-openms-tools/openms-on-galaxy.html"
    - title: Create high-performance tools
      subtitle: Develop high-performance tools or algorithms with the C++ OpenMS library
      terminal: true
      buttonText: Get Started
      bottomBorderRadius: true
      buttonLink: "https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/nightly/html/OpenMS_tutorial.html"

  keyfeatures:
    title: What is OpenMS ?
    subtitle: OpenMS offers an open-source C++ library (+ Python bindings) for LC/MS data management, analysis and visualization. It empowers rapid development of mass spectrometry related software. OpenMS is freely  available under the three clause BSD license and runs under Windows, macOS and Linux.  The OpenMS members have a strong commitment to creating an open, inclusive, and positive community. Please read the OpenMS Code of Conduct for guidance on how to interact with others in a way that makes the community thrive.
    features:
    - title: Proteomics
      text: Almost 200 ready-made and customisable tools for analysing your proteomics data. Combined in flexible workflows they provide solutions to a broad range of problems arising in proteomics labs.
      img: /images/content_images/keyfeatures/proteomics2.png
      url: /keyfeatures/proteomics
    - title: Metabolomics
      text: OpenMS provides a wide range of customisable tools, specifically designed for all steps in the analysis of your targeted and untargeted metabolomics data.
      img: /images/content_images/keyfeatures/metabolomics4.png
      url: /keyfeatures/metabolomics
    - title: Workflows
      text: Every tool that is developed within OpenMS is available on flexible, scalable and easy-to-use workflow engines (such as KNIME, Galaxy, and nextflow) facilitating reproducible science.
      img: /images/content_images/keyfeatures/workflows2.png
      url: /keyfeatures/workflows
  # tabs:
  #   title: ECOSYSTEM
  section5: false
  # casestudies:
  #   title: Users
  #   features:
  #   - title: Apply tools and run existing workflows
  #     text: Dummy text refers to the bits of content that are used to fill a website mock-up. This text helps web designers better envision how the website will look as a finished product. It is important to understand that dummy text has no meaning whatsoever.
  #     img: /images/content_images/keyfeatures/proteomics.jpeg
  #     alttext: First image of a black hole. It is an orange circle in a black background.
  #     url: /case-studies/blackhole-image
  #   - title: Modify and create own workflows
  #     text: Dummy text refers to the bits of content that are used to fill a website mock-up. This text helps web designers better envision how the website will look as a finished product. It is important to understand that dummy text has no meaning whatsoever.
  #     img: /images/content_images/keyfeatures/proteomics.jpeg
  #     alttext: Two orbs orbiting each other. They are displacing gravity around them.
  #     url: /case-studies/gw-discov


navbar:
  - title: News
    url: /news
  - title: Install
    url: https://openms.readthedocs.io/en/latest/openms-applications-and-tools/installation.html
  - title: Documentation
    url: https://openms.readthedocs.io/en/latest/index.html
  - title: Tutorials
    url: /tutorials
  - title: Community
    sublinks:
      - title: Communication
        url: /communication
      - title: Contribute
        url: /contribute
    url: /community
  - title: About Us
    sublinks:
      - title: OpenMS Project
        url: /about
      - title: Contributors
        url: /contributors
    url: /about
  - title: Use Cases
    url: /publications
    sublinks:
      - title: Applications
        url: /applications
      - title: Publications
        url: /publications
  - title: Help Request
    url: /help-request
    button: true
footer:
  title: OpenMS
  deployedBy: /images/deployed-by-netlify.png
  logo: 
  socialmediatitle: ""
  socialmedia:
  - link: https://github.com/OpenMS/OpenMS
    icon: github
  # - link: https://www.youtube.com/channel/
  #   icon: youtube
  - link: https://twitter.com/OpenMSTeam
    icon: twitter
  quicklinks:
    column1:
      title: ""
      links:
        - text: Install
          link: /install
        - text: Documentation
          link: https://openms.readthedocs.io/en/latest/
        - text: Citing OpenMS
          link: /citing-openms

    column2:
      links:
        - text: About us
          link: /about
        - text: Community
          link: /community
        - text: Contribute
          link: /contribute
        - text: Code of conduct
          link: /code-of-conduct
    column3:
      links:
        - text: Help
          link: /help
        - text: Terms of use
          link: /terms
        - text: Privacy
          link: /privacy
        - text: Press kit
          link: /press-kit
        - text: Jobs
          link: /jobs

